config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper

  authenticate :user, lambda { |u| u.admin? } do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end

  # Authentication
  devise_for :users, skip: [:sessions, :passwords, :confirmations, :registrations],
                     controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  as :user do
    # session handling
    get     '/entrar'  => 'devise/sessions#new',     as: 'new_user_session'
    post    '/entrar'  => 'devise/sessions#create',  as: 'user_session'
    delete  '/sair' => 'devise/sessions#destroy', as: 'destroy_user_session'

    # joining
    get   '/cadastrar' => 'devise/registrations#new',    as: 'new_user_registration'
    post  '/cadastrar' => 'devise/registrations#create', as: 'user_registration'

    scope '/minha-conta' do
      # password reset
      get   '/perdi-a-senha'       => 'devise/passwords#new',    as: 'new_user_password'
      put   '/perdi-a-senha'       => 'devise/passwords#update', as: 'user_password'
      post  '/perdi-a-senha'       => 'devise/passwords#create'
      get   '/perdi-a-senha/mudar' => 'devise/passwords#edit',   as: 'edit_user_password'

      # confirmation
      get   '/confirmacao'         => 'devise/confirmations#show',   as: 'user_confirmation'
      post  '/confirmacao'         => 'devise/confirmations#create'
      get   '/confirmacao/renviar' => 'devise/confirmations#new',    as: 'new_user_confirmation'

      # settings & cancellation
      get '/cancelar'   => 'devise/registrations#cancel', as: 'cancel_user_registration'
      get '/meus-dados' => 'devise/registrations#edit',   as: 'edit_user_registration'
      put '/meus-dados' => 'devise/registrations#update'

      # account deletion
      delete '' => 'devise/registrations#destroy'
    end
  end

  resources :groups, path: '/grupos', except: [:show] do
    put :classify, on: :member
    resources :members, path: '/participantes', only: [:index, :destroy] do
      get '/bets' => 'members#bets', as: 'bets'
    end

    resource :member, path: '/participante', only: [] do
      get    '/novo'     => 'members#new',    as: 'new'
      post   '/convidar' => 'members#invite', as: 'invite'
      put    '/aceitar'  => 'member#accept',  as: 'accept'
      delete '/'         => 'member#destroy', as: 'destroy'
    end
  end

  resources :bets, only: [:index, :update]

  resources :championships, except: :show

  resources :teams, except: :show

  resources :games, except: :show

  get '/sobre'       => 'pages#about', as: 'about'
  get '/regulamento' => 'pages#rule',  as: 'rule'

  root to: 'bets#index'
end

app/models/group.rb
class Group < ApplicationRecord
  ## associations
  belongs_to :admin, class_name: User
  belongs_to :championship
  has_many   :members, dependent: :destroy
  has_many   :users, through: :members

  ## validations
  validates :name,         presence: true, uniqueness: { scope: :championship }
  validates :admin,        presence: true
  validates :championship, presence: true

  ## methods
  def to_s
    name
  end

  def admin? user
    user == admin
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_common

  respond_to :html

  def index
    @my_groups = current_user.my_groups.includes(:championship)
    @members   = current_user.members.where.not(group: @my_groups.map(&:id))
    respond_with @my_groups
  end

  def new
    @my_group = current_user.my_groups.new
    respond_with @my_group
  end

  def create
    result = CreateGroup.call(params: group_params, user: current_user)
    @my_group = result.group

    if result.success?
      flash[:notice] = "Seu grupo #{@my_group} foi criado com sucesso"
    end

    respond_with @my_group, location: groups_path
  end

  def edit
    respond_with @my_group
  end

  def update
    flash[:notice] = "O grupo #{@my_group} foi alterado com sucesso" if @my_group.update(group_params)
    respond_with @my_group, location: groups_path
  end

  def classify
    if ClassifyGroupWorker.perform_async(@my_group.id)
      flash[:notice] = "O recálculo do ranking do #{@my_group} foi solicitado com sucesso, aguarde alguns instantes e atualize a página! (:"
    end

    respond_with @my_group, location: bets_path
  end

  def destroy
    @my_group.destroy
    flash[:notice] = "O seu grupo foi excluído com sucesso"
    respond_with @my_group
  end

private
  def set_common
    @my_group = current_user.my_groups.find(params[:id]) if params[:id]
  end

  def group_params
    params.require(:group).permit(:name, :championship_id)
  end
end

app/views/groups/edit.html.slim
- content_for :title
  = link_to "Grupos", groups_path
  |  >&nbsp;
  = @my_group

= simple_form_for(@my_group) do |f|
  = f.error_notification
  .form-inputs
    = f.input :name, required: true
  .form-actions
    = f.button :submit, "Salvar", class: "btn btn-primary"
    | &nbsp;
    = link_to "Cancelar", :back, class: "btn btn-danger"

app/views/groups/index.html.slim
- content_for :title
  | Grupos
  = link_to new_group_path, class: "btn btn-primary pull-right" do
    i.fa.fa-plus
    |  Adicionar grupo
h2
  | Meus grupos

- if @my_groups.present?
  table.table
    thead
      tr
        th[class="col-md-5"]
          | Nome
        th[class="col-md-4"]
          | Campeonato
        th[class="col-md-3"]
          |
    - for group in @my_groups do
      tbody
        tr
          td
            = group
          td
            = group.championship
          td.text-right
            = link_to group_members_path(group), class: "btn btn-default btn-xs" do
              i.fa.fa-users
              |  Participantes
            |&nbsp;
            = link_to edit_group_path(group), class: "btn btn-default btn-xs" do
              i.fa.fa-edit
              |  Editar
            |&nbsp;
            = link_to group, method: :delete, "data-confirm" => "Tem certeza que deseja excluir o grupo?\n\nVocê perderá todos os dados e usuários vinculados!", class: "btn btn-default btn-xs" do
              i.fa.fa-trash-o
              |  Excluir
- else
  div[class="alert alert-warning"]
    p
      | Você não criou nenhum grupo até agora. Acho que é uma ótima oportunidade, que tal&nbsp;
      = link_to "criar seu grupo", new_group_path
      | ? (:

- if @members.present?
  h2
    | Grupos que participo
  table.table
    thead
      tr
        th[class="col-md-5"]
          | Nome
        th[class="col-md-3"]
          | Campeonato
        th[class="col-md-2"]
          | Administrador
        th[class="col-md-2"]
          |
    - for member in @members do
      tbody
        tr
          td
            = member.group
          td
            = member.group.championship
          td
            = member.group.admin
          td.text-right
            - if member.invited?
              = link_to accept_group_member_path(member.group), method: :put, class: "btn btn-default btn-xs" do
                i.fa.fa-sign-in
                |  Aceitar
            | &nbsp;
            = link_to destroy_group_member_path(member.group), method: :delete, "data-confirm" => 'Tem certeza que deseja deixar de participar desse bolão?', class: "btn btn-default btn-xs" do
              i.fa.fa-sign-out
              |  Sair

app/views/groups/new.html.slim
- content_for :title
  = link_to "Grupos", groups_path
  |  > Adicionar
= simple_form_for(@my_group) do |f|
  = f.error_notification
  .form-inputs
    = f.input :name, required: true
    = f.association :championship, required: true
  .form-actions
    = f.button :submit, "Salvar", class: "btn btn-primary"
    | &nbsp;
    = link_to "Cancelar", :back, class: "btn btn-danger"