config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper

  authenticate :user, lambda { |u| u.admin? } do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end

  # Authentication
  devise_for :users, skip: [:sessions, :passwords, :confirmations, :registrations],
                     controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  as :user do
    # session handling
    get     '/entrar'  => 'devise/sessions#new',     as: 'new_user_session'
    post    '/entrar'  => 'devise/sessions#create',  as: 'user_session'
    delete  '/sair' => 'devise/sessions#destroy', as: 'destroy_user_session'

    # joining
    get   '/cadastrar' => 'devise/registrations#new',    as: 'new_user_registration'
    post  '/cadastrar' => 'devise/registrations#create', as: 'user_registration'

    scope '/minha-conta' do
      # password reset
      get   '/perdi-a-senha'       => 'devise/passwords#new',    as: 'new_user_password'
      put   '/perdi-a-senha'       => 'devise/passwords#update', as: 'user_password'
      post  '/perdi-a-senha'       => 'devise/passwords#create'
      get   '/perdi-a-senha/mudar' => 'devise/passwords#edit',   as: 'edit_user_password'

      # confirmation
      get   '/confirmacao'         => 'devise/confirmations#show',   as: 'user_confirmation'
      post  '/confirmacao'         => 'devise/confirmations#create'
      get   '/confirmacao/renviar' => 'devise/confirmations#new',    as: 'new_user_confirmation'

      # settings & cancellation
      get '/cancelar'   => 'devise/registrations#cancel', as: 'cancel_user_registration'
      get '/meus-dados' => 'devise/registrations#edit',   as: 'edit_user_registration'
      put '/meus-dados' => 'devise/registrations#update'

      # account deletion
      delete '' => 'devise/registrations#destroy'
    end
  end

  resources :groups, path: '/grupos', except: [:show] do
    put :classify, on: :member
    resources :members, path: '/participantes', only: [:index, :destroy] do
      get '/bets' => 'members#bets', as: 'bets'
    end

    resource :member, path: '/participante', only: [] do
      get    '/novo'     => 'members#new',    as: 'new'
      post   '/convidar' => 'members#invite', as: 'invite'
      put    '/aceitar'  => 'member#accept',  as: 'accept'
      delete '/'         => 'member#destroy', as: 'destroy'
    end
  end

  resources :bets, only: [:index, :update]

  resources :championships, except: :show

  resources :teams, except: :show

  resources :games, except: :show

  get '/sobre'       => 'pages#about', as: 'about'
  get '/regulamento' => 'pages#rule',  as: 'rule'

  root to: 'bets#index'
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Palpito.com.br
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false
    = javascript_include_tag 'application', 'data-turbolinks-track' => false
    = javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.6.0/underscore-min.js'
    = javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/backbone.js/1.1.2/backbone-min.js'
    = csrf_meta_tags
    /[if lt IE 9]
      = javascript_include_tag "http://html5shiv.googlecode.com/svn/trunk/html5.js"
    /[if lt IE 9]
      = javascript_include_tag "http://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"
      = javascript_include_tag "http://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"
    meta[http-equiv="X-UA-Compatible" content="IE=edge"]
  body
    div[class="navbar navbar-default navbar-fixed-top" role="navigation"]
      div.container
        div.navbar-header
          button.navbar-toggle[data-toggle="collapse" data-target=".navbar-collapse"]
            span.sr-only
              | Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to root_path, class: "navbar-brand" do
            strong
              | Palpito
            | .com.br
        div[class="collapse navbar-collapse"]
          ul[class="nav navbar-nav navbar-right"]
            - if user_signed_in?
              li
                ul.nav.navbar-nav
                  li.dropdown
                    - if current_user.groups.exists?
                      a[href="#" class="dropdown-toggle" data-toggle="dropdown"]
                        | Gerenciar bolão
                        b.caret
                      ul.dropdown-menu
                        li
                          = link_to 'Meus grupos', groups_path
                        - if current_user.try :admin?
                          li.divider
                          li.dropdown-header
                            | Administração
                          li
                            = link_to 'Campeonatos', championships_path
                            = link_to 'Times', teams_path
                            = link_to 'Jogos', games_path
                    - else
                      = link_to 'Crie um grupo!', new_group_path
              li
                ul[class="nav navbar-nav"]
                  li.dropdown
                    a[href="#" class="dropdown-toggle" data-toggle="dropdown"]
                      | Minha conta
                      b.caret
                    ul.dropdown-menu
                      li
                        = link_to "Meus dados", edit_user_registration_path
                      li
                        = link_to "Sair", destroy_user_session_path, method: :delete
            - else
              li
                = link_to "Entrar", new_user_session_path
              li
                = link_to "Cadastrar", new_user_registration_path

    div.container
      div.page-header
        h1
          = yield :title

      - flash.each do |name, msg|
        - if msg.is_a?(String)
          div[class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"]
            button[type="button" class="close" data-dismiss="alert" aria-hidden="true"]
              | &times;
            div
              = msg

      = yield

  footer.navbar.navbar-default.navbar-fixed-bottom.navbar-inverse
    div.container
      div.navbar-header
        = link_to root_path, class: "navbar-brand" do
          small
            | Palpito.com.br
            = " © 2010-#{Time.current.year}"
      ul.nav.nav-pills.pull-right
        li.btn
          = link_to "Regulamento", rule_path
        li.btn
          = link_to "Sobre", about_path