config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper

  authenticate :user, lambda { |u| u.admin? } do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end

  # Authentication
  devise_for :users, skip: [:sessions, :passwords, :confirmations, :registrations],
                     controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  as :user do
    # session handling
    get     '/entrar'  => 'devise/sessions#new',     as: 'new_user_session'
    post    '/entrar'  => 'devise/sessions#create',  as: 'user_session'
    delete  '/sair' => 'devise/sessions#destroy', as: 'destroy_user_session'

    # joining
    get   '/cadastrar' => 'devise/registrations#new',    as: 'new_user_registration'
    post  '/cadastrar' => 'devise/registrations#create', as: 'user_registration'

    scope '/minha-conta' do
      # password reset
      get   '/perdi-a-senha'       => 'devise/passwords#new',    as: 'new_user_password'
      put   '/perdi-a-senha'       => 'devise/passwords#update', as: 'user_password'
      post  '/perdi-a-senha'       => 'devise/passwords#create'
      get   '/perdi-a-senha/mudar' => 'devise/passwords#edit',   as: 'edit_user_password'

      # confirmation
      get   '/confirmacao'         => 'devise/confirmations#show',   as: 'user_confirmation'
      post  '/confirmacao'         => 'devise/confirmations#create'
      get   '/confirmacao/renviar' => 'devise/confirmations#new',    as: 'new_user_confirmation'

      # settings & cancellation
      get '/cancelar'   => 'devise/registrations#cancel', as: 'cancel_user_registration'
      get '/meus-dados' => 'devise/registrations#edit',   as: 'edit_user_registration'
      put '/meus-dados' => 'devise/registrations#update'

      # account deletion
      delete '' => 'devise/registrations#destroy'
    end
  end

  resources :groups, path: '/grupos', except: [:show] do
    put :classify, on: :member
    resources :members, path: '/participantes', only: [:index, :destroy] do
      get '/bets' => 'members#bets', as: 'bets'
    end

    resource :member, path: '/participante', only: [] do
      get    '/novo'     => 'members#new',    as: 'new'
      post   '/convidar' => 'members#invite', as: 'invite'
      put    '/aceitar'  => 'member#accept',  as: 'accept'
      delete '/'         => 'member#destroy', as: 'destroy'
    end
  end

  resources :bets, only: [:index, :update]

  resources :championships, except: :show

  resources :teams, except: :show

  resources :games, except: :show

  get '/sobre'       => 'pages#about', as: 'about'
  get '/regulamento' => 'pages#rule',  as: 'rule'

  root to: 'bets#index'
end

app/models/member.rb
class Member < ApplicationRecord
  ## associations
  belongs_to :group
  belongs_to :user

  ## validations
  validates :group,  presence: true, uniqueness: { scope: :user }
  validates :user,   presence: true
  validates :status, presence: true

  ## attributes
  enum status: { active: 0, pending: 1, invited: 2 }

  ## delegates
  delegate :nickname,  to: :user
  delegate :full_name, to: :user
  delegate :email,     to: :user
  delegate :to_s,      to: :user

  ## methods
  def rank_for!(day, points:, position:)
    if actual_position = positions.keys.reverse.first
      actual_position = Date.commercial(*actual_position.split('/').map(&:to_i))
    end

    if !actual_position || actual_position < day
      self.points = points
      self.position = position
    end

    self.positions[day.strftime('%Y/%W')] = position

    save!
  end

  def position_difference
    return 0 if positions.size < 2

    positions.sort.last(2).map(&:last).reduce(&:-)
  end
end

app/models/member_form.rb
# TODO: create a path for 'forms'?
class MemberForm
  include ActiveModel::Model

  ## attributes
  attr_accessor :email, :group

  ## validations
  validates :email, presence: true
  validates :group, presence: true
end

app/controllers/member_controller.rb
class MemberController < ApplicationController
  before_action :authenticate_user!
  before_action :set_common

  respond_to :html

  def accept
    if @member.active!
      flash[:notice] = "Você aceitou o convite para o #{@group}! Boa sorte!"
    end

    respond_with @member, location: groups_path
  end

  def destroy
    if @member.destroy
      flash[:notice] = "Você saiu do #{@group}! );"
    end

    respond_with @member, location: groups_path
  end

private
  def set_common
    @group  = current_user.groups.find(params[:group_id])
    @member = current_user.members.where(group_id: @group.id).first
  end

  def member_params
    params.require(:member_form).permit(:email).merge(group: @group)
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_my_group, except: :bets

  respond_to :html

  def index
    @members = @group.members
    respond_with @members
  end

  def new
    @member = MemberForm.new(group: @group)
    respond_with @member
  end

  def invite
    @member = MemberForm.new(member_params)
    result  = InviteMember.call(member: @member)

    if result.success?
      @member = result.member
      flash[:notice] = "Você convidou #{@member.email} com sucesso"
    end

    respond_with @member, location: group_members_path(@group)
  end

  def destroy
    @member = @group.members.find(params[:id])
    flash[:notice] = "Você removeu o #{@member.email} com sucesso" if @member.destroy

    respond_with @member, location: group_members_path(@group)
  end

  def bets
    # TODO choose better way
    request.variant = :mobile if browser.device.mobile?

    @group   = current_user.groups.find(params[:group_id])
    @member  = @group.members.find(params[:member_id])
    @members = @group.members.joins(:user).active.merge(User.confirmed).order(points: :desc)
    @week    = WeekNavigation.new(championship: @group.championship, day: params[:day])

    @bets   = @member.user.bets.
                joins(game: :championship).
                includes(game: [:team_home, :team_away, :championship]).
                merge(Game.played).
                where(
                  games: { played_at: @week.to_range, championship_id: @group.championship_id }
                ).
                order('"games"."played_at" ASC')

    respond_with @bets
  end

private
  def set_my_group
    @group = current_user.my_groups.find(params[:group_id])
  end

  def member_params
    params.require(:member_form).permit(:email).merge(group: @group)
  end
end

app/views/members/_week_navigation.html.erb
<ul class="pager">
  <% if @week.previous? %>
    <li class="previous">
      <%= link_to '←', group_member_bets_path(@group, @member, day: @week.previous) %>
    </li>
  <% else %>
    <li class='previous disabled'>
      <a>←</a>
    </li>
  <% end %>
  <li class="week">
    Semana <%= @week.week %>:
    <%= @week.start.strftime("%d/%m") %> a <%= @week.finish.strftime("%d/%m") %>
  </li>
  <% if @week.next? %>
    <li class="next">
      <%= link_to '→', group_member_bets_path(@group, @member, day: @week.next) %>
    </li>
  <% else %>
    <li class="next disabled">
      <a>→</a>
    </li>
  <% end %>
</ul>

app/views/members/bets.html+mobile.erb
<% content_for :title do %>
  Palpites de <%= @member %> no <%= @group %>
<% end %>

<div class="col-xs-12">
  <%= render "week_navigation" %>

  <div id="bets" class="list-group row">
  <% @bets.each do |bet| %>
    <div class="list-group-item bet">
      <div class="col-xs-1">
        <div class="text-center bg-success"><strong><%= I18n.t("date.abbr_day_names")[bet.game.played_at.strftime("%w").to_i] %></strong></div>
        <div class="text-center"><%= bet.game.played_at.strftime("%H:%M") %></div>
        <div class="text-center"><small class="text-muted"><%= bet.game.played_at.strftime("%d/%m") %></small></div>
      </div>

      <div class="col-xs-10 teams">
        <div class="col-xs-3 team-name text-right"><%= bet.team_home %></div>
        <div class="col-xs-1 team-image text-center"><%= image_tag bet.team_home.image.url, class: "img-responsive" %></div>
        <div class="col-xs-4 text-center goal">
          <%= text_field_tag "home_goals", bet.team_home_goals %>
          <span class="vs">x</span>
          <%= text_field_tag "away_goals", bet.team_away_goals %>
        </div>
        <div class="col-xs-1 team-image text-center"><%= image_tag bet.team_away.image.url, class: "img-responsive" %></div>
        <div class="col-xs-3 team-name"><%= bet.team_away %></div>
      </div>

      <div class="col-xs-1 text-center points"><%= bet.points %></div>
    </div>
  <% end %>
  </div>
</div>

<%= render "shared/ranking" %>

app/views/members/bets.html.erb
<% content_for :title do %>
  Palpites de <%= @member %> no <%= @group %>
<% end %>

<div class="col-sm-9">
  <%= render "week_navigation" %>

  <div id="bets" class="list-group row">
  <% @bets.each do |bet| %>
    <div class="list-group-item bet">
      <div class="col-sm-1">
        <div class="text-center bg-success"><strong><%= I18n.t("date.abbr_day_names")[bet.game.played_at.strftime("%w").to_i] %></strong></div>
        <div class="text-center"><%= bet.game.played_at.strftime("%H:%M") %></div>
        <div class="text-center"><small class="text-muted"><%= bet.game.played_at.strftime("%d/%m") %></small></div>
      </div>

      <div class="col-sm-10 teams">
        <div class="col-sm-3 team-name text-right"><%= bet.team_home %></div>
        <div class="col-sm-1 team-image text-center"><%= image_tag bet.team_home.image.url, class: "img-responsive" %></div>
        <div class="col-sm-4 text-center goal">
          <%= text_field_tag "home_goals", bet.team_home_goals %>
          <span class="vs">x</span>
          <%= text_field_tag "away_goals", bet.team_away_goals %>
        </div>
        <div class="col-sm-1 team-image text-center"><%= image_tag bet.team_away.image.url, class: "img-responsive" %></div>
        <div class="col-sm-3 team-name"><%= bet.team_away %></div>
      </div>

      <div class="col-sm-1 text-center points"><%= bet.points %></div>
    </div>
  <% end %>
  </div>
</div>

<%= render "shared/ranking" %>

app/views/members/index.html.slim
- content_for :title
  = link_to "Grupos", groups_path
  |  > Participantes do #{@group}
  = link_to new_group_member_path(@group), class: "btn btn-primary pull-right"
    i.fa.fa-envelope-o
    |  Convidar novo membro

- if @members.present?
  table.table
    thead
      tr
        th.col-md-2
          | Apelido
        th.col-md-3
          | Nome
        th.col-md-3
          | E-mail
        th.col-md-1
          | Status
        th.col-md-2
          |
    - for member in @members do
      tbody
        tr
          td
            = member.nickname
          td
            = member.full_name
          td
            = member.email
          td
            = member.status
          td.text-right
            = link_to group_member_path(@group, member), method: :delete, "data-confirm" => "Tem certeza que deseja excluir o participante?", class: "btn btn-default btn-xs" do
              i.fa.fa-trash-o
              |  Excluir
- else
  div[class="alert alert-warning"]
    p
      | O que?! Você não tem nenhum participante no seu grupo?
    p
      | Está mais que na hora de&nbsp;
      = link_to "convidar alguém", new_group_member_path(@group)
      |  para participar!

app/views/members/new.html.slim
- content_for :title
  = link_to "Grupos", groups_path
  |  >&nbsp;
  = link_to "Participantes do #{@group}", group_members_path(@group)
= simple_form_for([@group, @member], url: invite_group_member_path(@group, @member)) do |f|
  = f.error_notification
  .form-inputs
    = f.input :group, readonly: true
    = f.input :email, required: true
  .form-actions
    = f.button :submit, "Convidar participante", class: "btn btn-primary"
    | &nbsp;
    = link_to "Cancelar", :back, class: "btn btn-danger"